,1:number,2:error_lines,3:error_logs,4:error_time
0,128,226,"HTTPConnectionPool(host='localhost', port=41820): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0daf5a668>: Failed to establish a new connection: [Errno 111] Connection refused',))",18:01:10
1,811,237,'NoneType' object has no attribute 'send_keys',19:42:54
