Error 'HTTPConnectionPool(host='localhost', port=36922): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1eb3e3de48>: Failed to establish a new connection: [Errno 111] Connection refused',))' happened on line 215    Mon May 20 19:24:54 2019
Error ''NoneType' object has no attribute 'send_keys'' happened on line 226    Mon May 20 19:27:27 2019
